DROP RULE IF EXISTS "CANDIDATES_on_duplicate_ignore" ON CANDIDATES;
DROP RULE IF EXISTS "COMMITTEES_on_duplicate_ignore" ON COMMITTEES;
DROP RULE IF EXISTS "IND_CONTRIBS_on_duplicate_ignore" ON IND_CONTRIBS;
DROP RULE IF EXISTS "COMM_CONTRIBS_on_duplicate_ignore" ON COMM_CONTRIBS;
DROP RULE IF EXISTS "COMM_CAND_LINKAGES_on_duplicate_ignore" ON COMM_CAND_LINKAGES;

DROP TABLE IF EXISTS COMM_CAND_LINKAGES;
DROP TABLE IF EXISTS COMM_CONTRIBS;
DROP TABLE IF EXISTS IND_CONTRIBS;
DROP TABLE IF EXISTS COMMITTEES;
DROP TABLE IF EXISTS CANDIDATES;

CREATE TABLE CANDIDATES(
    CAND_ID VARCHAR(9) PRIMARY KEY,
    CAND_NAME VARCHAR(200),
    CAND_ELECTION_YR NUMERIC(4),
    CAND_CITY VARCHAR(30),
    CAND_ST VARCHAR(2),
    CAND_ZIP VARCHAR(9),
    CAND_OFFICE_ST VARCHAR(2),
    CAND_OFFICE VARCHAR(1),
    CAND_OFFICE_DISTRICT VARCHAR(2),
    CAND_PTY_AFFILIATION VARCHAR(3)
);

CREATE TABLE COMMITTEES(
    CMTE_ID VARCHAR(9) PRIMARY KEY,
    CMTE_NM VARCHAR(200),
    CMTE_CITY VARCHAR(30),
    CMTE_ST VARCHAR(2),
    CMTE_ZIP VARCHAR(9),
    CAND_ID VARCHAR(9),
    CMTE_TP VARCHAR(1),
    CMTE_PTY_AFFILIATION VARCHAR(3),
    FOREIGN KEY (CAND_ID) REFERENCES CANDIDATES(CAND_ID)
);

CREATE TABLE COMM_CAND_LINKAGES(
    LINKAGE_ID VARCHAR(9) PRIMARY KEY,
    CAND_ID VARCHAR(9),
    CAND_ELECTION_YR NUMERIC(4),
    FEC_ELECTION_YR NUMERIC(4),
    CMTE_ID VARCHAR(9),
    CMTE_TP VARCHAR(1),
    CMTE_DSGN VARCHAR(1),
    FOREIGN KEY (CAND_ID) REFERENCES CANDIDATES (CAND_ID),
    FOREIGN KEY (CMTE_ID) REFERENCES COMMITTEES (CMTE_ID)
);

CREATE TABLE COMM_CONTRIBS(
    SUB_ID NUMERIC(19) PRIMARY KEY,
    CMTE_ID VARCHAR(9),
    ENTITY_TP VARCHAR(3),
    NAME VARCHAR(200),
    CITY VARCHAR(30),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(9),
    CAND_ID VARCHAR(9),
    TRANSACTION_AMT NUMERIC(14,2),
    TRANSACTION_DT DATE,
    FOREIGN KEY (CAND_ID) REFERENCES CANDIDATES (CAND_ID),
    FOREIGN KEY (CMTE_ID) REFERENCES COMMITTEES (CMTE_ID)
);

CREATE TABLE IND_CONTRIBS(
    SUB_ID NUMERIC(19) PRIMARY KEY,
    CMTE_ID VARCHAR(9),
    ENTITY_TP VARCHAR(3),
    NAME VARCHAR(200),
    CITY VARCHAR(30),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(9),
    TRANSACTION_AMT NUMERIC(14,2),
    TRANSACTION_DT DATE,
    FOREIGN KEY (CMTE_ID) REFERENCES COMMITTEES (CMTE_ID)
);

CREATE INDEX ON COMMITTEES (CMTE_ZIP);
CREATE INDEX ON COMMITTEES (CAND_ID);

CREATE INDEX ON CANDIDATES (CAND_ELECTION_YR);
CREATE INDEX ON CANDIDATES (CAND_ZIP);

CREATE INDEX ON COMM_CAND_LINKAGES (CAND_ELECTION_YR);
CREATE INDEX ON COMM_CAND_LINKAGES (CMTE_ID);

CREATE INDEX ON COMM_CONTRIBS (ZIP_CODE);
CREATE INDEX ON COMM_CONTRIBS (CAND_ID);
CREATE INDEX ON COMM_CONTRIBS (TRANSACTION_DT);
CREATE INDEX ON COMM_CONTRIBS (TRANSACTION_AMT);

CREATE INDEX ON IND_CONTRIBS (ZIP_CODE);
CREATE INDEX ON IND_CONTRIBS (TRANSACTION_DT);
CREATE INDEX ON IND_CONTRIBS (TRANSACTION_AMT);

CREATE RULE "CANDIDATES_on_duplicate_ignore" AS ON INSERT TO CANDIDATES
  WHERE EXISTS(SELECT 1 FROM CANDIDATES
                WHERE (CAND_ID)=(NEW.CAND_ID))
  DO INSTEAD NOTHING;

CREATE RULE "COMMITTEES_on_duplicate_ignore" AS ON INSERT TO COMMITTEES
  WHERE EXISTS(SELECT 1 FROM COMMITTEES
              WHERE (CMTE_ID)=(NEW.CMTE_ID))
  DO INSTEAD NOTHING;

CREATE RULE "IND_CONTRIBS_on_duplicate_ignore" AS ON INSERT TO IND_CONTRIBS
  WHERE EXISTS(SELECT 1 FROM IND_CONTRIBS
              WHERE (SUB_ID)=(NEW.SUB_ID))
  DO INSTEAD NOTHING;

CREATE RULE "COMM_CONTRIBS_on_duplicate_ignore" AS ON INSERT TO COMM_CONTRIBS
  WHERE EXISTS(SELECT 1 FROM COMM_CONTRIBS
              WHERE (SUB_ID)=(NEW.SUB_ID))
  DO INSTEAD NOTHING;

CREATE RULE "COMM_CAND_LINKAGES_on_duplicate_ignore" AS ON INSERT TO COMM_CAND_LINKAGES
  WHERE EXISTS(SELECT 1 FROM COMM_CAND_LINKAGES
              WHERE (LINKAGE_ID)=(NEW.LINKAGE_ID))
  DO INSTEAD NOTHING;
